services:
  parking.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking.api
    environment:
      ENVIRONMENT: production
      HTTP_PORT: 8080
      AUTH_SECRET: ######
      DATABASE_URI: postgres://postgres:password123@parking.db:5432/parkinglot
      MINIO_ENDPOINT: parking.minio:9000
      MINIO_ACCESSKEY: 1d1KqQif0abfpxQaxyy0
      MINIO_SECRETKEY: i9n4WD3PFSzc6XFZkow69UWV5dGx6bZbmMIjaNlU
      MINIO_BUCKET: goparking
      #      MINIO_BASEURL: http://139.59.250.218:9000
      #      MINIO_USESSL: false
      #      MINIO_BASEURL: http://goparking.duckdns.org:9000
      #      MINIO_USESSL: false
      MINIO_BASEURL: https://goparking.duckdns.org/minio/
      MINIO_USESSL: true
    depends_on:
      - parking.db
      - parking.minio
    restart: unless-stopped
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: parking.nginx
    ports:
      - "8080:80" # 🛠️ API HTTP
      - "8443:443" # 🛠️ API HTTPS
    depends_on:
      - parking.api
      - parking.minio
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  parking.db:
    image: postgres:16
    container_name: parking.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: parkinglot
    ports:
      - "5433:5432"
    volumes:
      - parking_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  parking.minio:
    image: minio/minio:latest
    container_name: parking.minio
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    restart: unless-stopped
    volumes:
      - parking_minio_data:/data
      - parking_minio_config:/root/.minio
      - /etc/letsencrypt:/etc/minio/certs:ro
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"

networks:
  default:
    name: parking
    driver: bridge

volumes:
  parking_postgres_data:
    name: parking_postgres_data
  parking_minio_data:
    name: parking_minio_data
  parking_minio_config:
    name: parking_minio_config





