services:
  parking.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking.api
    environment:
        ENVIRONMENT: production
        HTTP_PORT: 8080
        GRPC_PORT: 50051
        AUTH_SECRET: ######
        ACCESS_TOKEN_DURATION: 15m
        REFRESH_TOKEN_DURATION: 24h
        DATABASE_URI: postgres://postgres:password123@parking.db:5432/parkinglot
        MINIO_ENDPOINT: parking.minio:9000
        MINIO_ACCESSKEY: 3SYhDzVQBrLI9SzRB1zR
        MINIO_SECRETKEY: 8LJFPwOg4jscApFpAwawnbTKHNcyTd6y60mOzZbs
        MINIO_BUCKET: goparking
        MINIO_BASEURL: http://localhost:9000
        MINIO_USESSL: false
        REDIS_URI: parking.redis:6379
        REDIS_PASSWORD: password
        REDIS_DB: 0
    ports:
      - "8002:8080"
    depends_on:
      - parking.db
      - parking.minio
      - parking.redis
    restart: unless-stopped
    volumes:
      - .:/app

  parking.db:
    image: postgres:16
    container_name: parking.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: parkinglot
    ports:
      - "5433:5432"
    volumes:
      - parking_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  parking.minio:
    image: minio/minio:latest
    container_name: parking.minio
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    restart: unless-stopped
    volumes:
      - parking_minio_data:/data
      - parking_minio_config:/root/.minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"

  parking.redis:
    image: redis:latest
    container_name: parking.redis
    restart: unless-stopped
    ports:
      - "6389:6379"
    volumes:
      - parking_redis_data:/data
    environment:
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
      REDIS_DATABASES: 0
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "password" ]

networks:
  default:
    name: parking
    driver: bridge


volumes:
  parking_postgres_data:
    name: parking_postgres_data
  parking_minio_data:
    name: parking_minio_data
  parking_minio_config:
    name: parking_minio_config
  parking_redis_data:
    name: parking_redis_data
